id: 364b49a708004d71acc03fadc463c8f5
initial_creation_type: ocr
source_metadata:
  volumes:
    b3aef000a4594f6ebcda27eda6bdbc14:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: འཕགས་པ་རྣམ་པར་མི་རྟོག་པར་འཇུག་པའི་གཟུངས་ཀྱི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
